import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:plugin_crypto/plugin_crypto.dart';
import 'package:plugin_crypto/src/metrics/metrics_collector.dart';

bool _allZero(Uint8List b) => b.every((e) => e == 0);

void main() {
  final m = MetricsCollector.instance;
  m?.startZone('zone03', 'AES-CBC');

  group('RAND_bytes', () {
    test('generates correct length', () {
      final api = PluginCryptoAPI.instance;

      expect(api.randomBytes(16).length, equals(16));
      expect(api.randomBytes(32).length, equals(32));
      expect(api.randomBytes(1024).length, equals(1024));
      expect(api.randomBytes(1).length, equals(1));
      expect(api.randomBytes(256).length, equals(256));
    });

    test('two consecutive calls produce different data', () {
      final api = PluginCryptoAPI.instance;

      final first = api.randomBytes(32);
      final second = api.randomBytes(32);

      expect(first, isNot(equals(second)));
    });

    test('generated bytes are not all zeros', () {
      final api = PluginCryptoAPI.instance;

      final bytes = api.randomBytes(32);

      expect(_allZero(bytes), isFalse);
    });
  });

  group('Random edge cases', () {
    test('length 0 returns empty list', () {
      final api = PluginCryptoAPI.instance;

      final result = api.randomBytes(0);

      expect(result, isEmpty);
    });
  });

  m?.endZone();
}
